### ISSUE TITLE
备忘：几个小BUG希望抽时间修复一下

### ISSUE THREAD

**Issue by dinphy** [kingwrcy/moments#103]
### 两个小BUG

- TAG页或详情页，首次进入，图片不能查看大图，刷新后可以。
- 暗色模式只在当前页生效，切换页面就反弹了。

### 音乐插入（优化建议）

- 直接嵌入网易云音乐的代码，PC端能用，但控制台报错；移动端浏览器有的能显示播放器，有的不行。能显示的浏览器呢，播放器右边部分溢出了，更改宽度没效果。

**Comment by kingwrcy** [comment]
2个bug收到,下个版本尽量fix掉.
网易云音乐这个手机端无法展示是已知问题,pc上使用chrome模拟又是正常的,所以比较难以调试.有空会尝试解决.
