### ISSUE TITLE
能否增加图片压缩功能

### ISSUE THREAD

**Issue by xiaokaRepo** [kingwrcy/moments#106]
目前手机拍照照片都很大，是否可以使用[squoosh](https://squoosh.app)类似无损压缩的方式来进行图片优化，这样可以也加快访问速度，我查了下有@squoosh/lib这个 npm包，奈何我不会前端开发，所以希望大佬有时间可以考虑下此功能🙏

**Comment by kingwrcy** [comment]
基于2点考虑不添加压缩功能:

1. 现在图片存本地的基本没有,基本都是存s3,为了速度考虑,也为了图片的持久存储着想,而一般的S3都已经提供了压缩图片的方法,而且基本都是0配置,只需要在后台的配置的`后缀`一栏填上S3支持的压缩图片的后缀即可.
2. 本项目为了提升上传图片的效率,图片是不经过服务端,图片上传是直接前端直连S3存储的,所以没机会压缩图片,图片压缩一般都需要node环境,也就是要在后端才能实现压缩,所以目前无法接入压缩功能.

如果你找不到支持图片压缩,又免费的s3,建议你使用[缤纷云](https://www.bitiful.com/) 基本等于免费,免费压缩图片,保护原图.
