### ISSUE TITLE
3个更新建议

### ISSUE THREAD

**Issue by angeljie** [kingwrcy/moments#116]
1. 在进入任何一个单独的帖子页面后，可以点击右上角大头像，回到首页。现在要点击左上角的”返回“，还是有点不方便；
2. 我把不同的帖子加上#tag，随后点击tag后，可以筛选出该tag下所有帖子，这个没问题。但当我在这个tag页面下，直接点击另外一个tag，页面是无法跳转的。也就是/?tag=XXX 链接下的页面之间无法直接跳转。
3. “使用在线图片”，发布之后，再发一个新帖子时，那个在线图片链接还在，需要点击手动清除。下个版本是否可以在点击“确认”或者点击“发布”之后，自动把在线图片的链接给清空？这样再发下一个帖子时，就不需要再手动点击清空了。

**Comment by kingwrcy** [comment]
已修发,下个版本会发布.
