### ISSUE TITLE
希望能增加一个搜索功能和日历模块

### ISSUE THREAD

**Issue by zwjdujin** [kingwrcy/moments#117]
希望能增加个搜索功能，毕竟内容越来越多之后，有时候想看看之前发的内容得不断的拉，能加一个搜索功能后，可以根据记忆搜索关键词快速定位到相关内容。

同时还希望有个日历模块，可以按日或者按月按年查看相应内容。

**Comment by kingwrcy** [comment]
主要是ui上已经不太能容得下日历控件了,容我考虑下.

**Comment by zwjdujin** [comment]
> 主要是ui上已经不太能容得下日历控件了,容我考虑下.

是否可以增加个页面作为日历展示呢？又能作为归档页快速筛选查看。

**Comment by dianso** [comment]
期待这个功能~

**Comment by kingwrcy** [comment]
v0.2.1会加上这个功能,下面是预览图

![image](https://github.com/user-attachments/assets/a8e63b19-c12c-46ca-aeaf-754da0dd589a)

**Comment by kingwrcy** [comment]
已经增加了.更新到0.2.1即可

**Comment by zwjdujin** [comment]
> 已经增加了.更新到0.2.1即可

老大牛逼plus
