### ISSUE TITLE
增加支持删除指定评论功能

### ISSUE THREAD

**Issue by 80imike** [kingwrcy/moments#12]
如果有恶意评论包含一些非法内容，不能删除就比较麻烦了

现在的评论管理员也是不能删除的，只能删除整条朋友圈。

希望增加下这个功能。

**Comment by kingwrcy** [comment]
已支持 , https://github.com/kingwrcy/moments/commit/35beabb38048c1e85010a9233d8c0b6d36d27be2
v0.0.6将支持
