### ISSUE TITLE
原本是默认数据库，如何转移到S3存储？

### ISSUE THREAD

**Issue by zwjdujin** [kingwrcy/moments#130]
请问一下：一开始原本是默认数据库，等后面想转移数据太麻烦，想直接数据放在S3存储，请问如何将数据转移到S3存储？

**Comment by kingwrcy** [comment]
不支持,目前只支持本地文件,你可以定期备份/app/data目录.

**Comment by zwjdujin** [comment]
> 不支持,目前只支持本地文件,你可以定期备份/app/data目录.

感谢解答
