### ISSUE TITLE
集成 Pushoo.js 以实现评论消息 IM 推送

### ISSUE THREAD

**Issue by ChaiByte** [kingwrcy/moments#131]
最近在玩各种支持评论的项目，集成 Twikoo 评论系统的时候发现了这个玩意： [pushoo.js](https://pushoo.js.org/)

> 消息推送平台多用于在特定的场合提醒使用者，例如：博客收到评论、服务器告警、油价上涨、每日签到结果推送、家中饲养的鸽子外出、飞回，等等……自从方糖气球推出 Server 酱以来，消息推送平台逐渐多样化，他们遵循的 API 格式却很混乱。

> 有的是 URL 地址传参，有的是 form 表单传参，有的是 JSON 传参，暂时还没看到 XML 传参的；
有的正文支持 Markdown，有的正文支持 HTML，有的正文支持纯文本；
有的支持标题，有的不支持标题。

项目依赖主要是 `axios`, 作者有考虑集成一下吗，我试了试用来绑定企业微信，消息同步发送到自己的个人微信，如果手头没注意邮件提醒电话，微信能通知一下，感觉也挺好的。

**Comment by kingwrcy** [comment]
集成没问题,问题是集成了干啥?有评论了通知吗?

**Comment by ChaiByte** [comment]
> 集成没问题,问题是集成了干啥?有评论了通知吗?

其他用户不知道这个需求强不强，可以搁置一段时间看看其他人会不会也提出类似的请求。

我个人给出的理由可能倾向于使用习惯，我看 IM 软件的频率远高于看邮箱，对于一些评论会希望第一时间回复...

另外 Twikoo 的操作是比较骚的，它默认没有过 XX 云内容安全自动检测的评论会转人工审核，依旧有人工通过的可能性，可能是考虑误报？ 🤷‍♂️🤷‍♂️🤷‍♂️ 不得而知

**Comment by kingwrcy** [comment]
v0.2.1 已经全面改成了Go作为服务端了,所以这个NodeJS 的SDK已经无法使用了,所以无法接入了.
