### ISSUE TITLE
能否批量导出数据？

### ISSUE THREAD

**Issue by zwjdujin** [kingwrcy/moments#132]
如果因为某些原因不想继续维护网站，能否批量导出数据到本地？

**Comment by kingwrcy** [comment]
直接复制/app/data目录就行

**Comment by zwjdujin** [comment]
> 直接复制/app/data目录就行

我的意思是能不能导出文本内容及附件，比如导出excel或者txt等可视化数据。

**Comment by kingwrcy** [comment]
目前不支持
