### ISSUE TITLE
被人恶意攻击了

### ISSUE THREAD

**Issue by adozhao** [kingwrcy/moments#135]
被有心人恶意攻击了，导致网站都废了都，有没有可能增加评论审核，关闭评论之类的功能杜绝这个现象， 相关网址：https://moments.ado.zone/

![image](https://github.com/kingwrcy/moments/assets/23180747/01ab92c0-b776-4b96-9fcc-ee1964804223)

**Comment by adozhao** [comment]
还有，这么多评论删除的话不得搞死我~

**Comment by kingwrcy** [comment]
支持了Google RecaptchaV3,自己研究下如何配置吧
配置了之后无法通过接口发表评论,一定程度上能防止吧.

上面这个你直接删除这条发言就行.或者有能力的上数据库里删除.

**Comment by adozhao** [comment]
没起到任何作用，今早又来攻击了，我只能被迫把整个服务停掉，这个已经是系统的重大漏洞了我觉得，只要能够评论交互之类的如果没有限制那就是有问题的

**Comment by kingwrcy** [comment]
关掉评论啊,可以配置为不开启的

**Comment by adozhao** [comment]
> 关掉评论啊,可以配置为不开启的

评论关闭了，但是还是能搞我~ 是不是有漏洞
![image](https://github.com/kingwrcy/moments/assets/23180747/594700ab-a288-4d5b-ae8e-5f2fe6787b2f)
