### ISSUE TITLE
docker版本0.1.9升级到0.2无法登录

### ISSUE THREAD

**Issue by huyiwan** [kingwrcy/moments#145]
docker版本0.1.9升级到0.2无法登录

**Comment by 939740372** [comment]
确实
{
    "url": "/api/user/login",
    "statusCode": 500,
    "statusMessage": "",
    "message": "secretOrPrivateKey must have a value",
    "stack": ""
}

**Comment by 939740372** [comment]
-- 自定义jwt密钥(从0.2版本开始必填,不填无法使用)
NUXT_JWT_KEY=自定义jwt密钥,可以自己随机生成
是这个原因吗

**Comment by kingwrcy** [comment]
是的,必须配置这个密钥,在docker启动的环境变量里指定即可.

**Comment by dinphy** [comment]
> -- 自定义jwt密钥(从0.2版本开始必填,不填无法使用) NUXT_JWT_KEY=自定义jwt密钥,可以自己随机生成 是这个原因吗? docker 启动貌似没地方配置

```python
docker run --restart=always --name moments -e NUXT_JWT_KEY=ZAkzv09rdrQTVXUk -d -v /docker/data/moments:/app/data -p 3000:3000 kingwrcy/moments:0.2
```
通过执行这一条命令能搞定。
