### ISSUE TITLE
修改<video> 标签以避免下载整个视频文件

### ISSUE THREAD

**Issue by evaniswong** [kingwrcy/moments#152]
现在的信息流中， post中的视频会被预下载，导致加载很慢。
搜索了一下 ，好像可以在<video> 标签中增加  preload="metadata" ，然后在source 中添加#t=1 来加载第一秒的画面作为预览图。

`<video> 标签中增加  preload="metadata" ，然后在source 中添加#t=1 来加载第一秒的画面作为预览图。`

信息来自
https://stackoverflow.com/questions/65862218/dont-preload-video-but-still-show-thumbnail

**Comment by kingwrcy** [comment]
加上了,下个版本发布,看看效果到时.
