### ISSUE TITLE
自定义位置记住内容

### ISSUE THREAD

**Issue by Jonnyan404** [kingwrcy/moments#16]
不然每次都要去输入一遍位置信息  挺累的

**Comment by kingwrcy** [comment]
记住最后一个还是记住每次输入的呢?

**Comment by Jonnyan404** [comment]
> 记住最后一个还是记住每次输入的呢?

最后一个也够用
全部记住,可以方便选择,更方便,但要有个删除键

**Comment by kingwrcy** [comment]
那这样一会儿又有人提了,怎么每次发言都带上上次的位置了,还要手动删除.
还是自动的好,不知道哪里有个人能免费使用的自动定位的api?

**Comment by Jonnyan404** [comment]
![image](https://github.com/kingwrcy/moments/assets/20352705/455faf61-e7e0-426d-bf02-9046a3998a1c)

**Comment by kingwrcy** [comment]
由于 [vue-shadcn ui](https://www.shadcn-vue.com/) 库中暂无类似ui组件,故先搁置了.
