### ISSUE TITLE
大佬，请问能否支持发布看书纪录（支持起点/番茄这些小说网站）

### ISSUE THREAD

**Issue by dianso** [kingwrcy/moments#160]
大佬，请问能否支持发布看书纪录（支持起点/番茄这些小说网站）

https://fanqienovel.com/
https://www.qidian.com/

输入小说id，能像豆瓣一样
豆瓣偏向于实体书，我还是很喜欢看小说的。

**Comment by kingwrcy** [comment]
暂无计划,需要的人多了,会考虑的.

**Comment by uubbbb** [comment]
小说网站可太多了，接入优书网或者推书君这种小说评分网站还靠谱点，但是书也不全。

**Comment by kingwrcy** [comment]
一个个的接基本不可能，有api的可以通知我，目前豆瓣是爬取的，费时费力，如果有api可以考虑下

**Comment by dianso** [comment]
> 一个个的接基本不可能，有api的可以通知我，目前豆瓣是爬取的，费时费力，如果有api可以考虑下

优书网比较全（https://www.yousuu.com/）可惜前几天被龙空卖了数据，现在经常跳到赌博网站。

还有两个比较全的，一个是类似豆瓣全网抓去各个小说站，推书君：https://www.tuishujun.com/

还有个就是只抓取阅文旗下七八个站的qidiantu：https://www.qidiantu.com/

都没有api，只能爬取
