### ISSUE TITLE
嵌入网易云音乐失败

### ISSUE THREAD

**Issue by piecepaper** [kingwrcy/moments#169]
根据教程 https://jerry.mblog.club/simple-moments-import-music-and-video

添加网易云音乐, 粘贴HTML代码. 确定后没有反应

各位大佬们, 帮忙看看是为啥呀

**Comment by kingwrcy** [comment]
新版本的不是这样用了,等下个版本吧,下个版本讲会说如何引入.

**Comment by piecepaper** [comment]
👍 好的, 期待下一个版本
