### ISSUE TITLE
发表的内容，默认显示内容太少了，能否支持自定义？

### ISSUE THREAD

**Issue by 80imike** [kingwrcy/moments#17]
发表的内容，默认只显示了很少内容。可不可以多显示几行？

最好可以支持下自定义设置显示几行，就更棒了

**Comment by kingwrcy** [comment]
要支持的自定义参数太多了,本项目本意是朋友圈,目前是超过4行就折叠.
不适合用来发长篇大论,文章适合使用博客等平台发布.

见谅.
