### ISSUE TITLE
docker 更新后，login无法登录，、

### ISSUE THREAD

**Issue by slynnnn** [kingwrcy/moments#174]
docker 更新后，login无法登录，账户和密码错误的时候提示账户或密码有错误，但是正确后，点击登录却没有反应。更新之前一直很好用，更新这个版本后，就这样了。

**Comment by kingwrcy** [comment]
我还没发布版本,你更新了什么?从0.1.9更新到了0.2 吗?
0.2 有个环境变量是必须配置的,不配置无法登录,readme里有写.

```
-- 自定义jwt密钥(从0.2版本开始必填,不填无法使用)
NUXT_JWT_KEY=自定义jwt密钥,可以自己随机生成
```
