### ISSUE TITLE
编辑和发送内容后，不能正常缩放显示

### ISSUE THREAD

**Issue by slynnnn** [kingwrcy/moments#177]
每次编辑和完成后，需要手动调整才能全屏显示，麻烦有空处理一下，谢谢。iPhone 15 ios18

![IMG_0561](https://github.com/user-attachments/assets/c1d57cf1-e83f-4dbf-a343-cc89a62ee2cc)

![IMG_0559](https://github.com/user-attachments/assets/64b0b466-00e7-4b47-9e62-51e1b5c5bf99)

**Comment by kingwrcy** [comment]
android chrome浏览器目前没遇到这个问题.
点击发表按钮,发表成功之后是跳转到首页,你意思是跳到首页后,首页不能完整显示吗?

**Comment by slynnnn** [comment]
苹果safari是这样的，编辑的过程中就会边宽一些。发布成功后，还保持着变宽的状态，需要手动缩小才能全屏显示。

**Comment by kingwrcy** [comment]
问题应该在这 -> 编辑的过程中就会边宽一些 
等我复现后尝试修复下吧.

**Comment by slynnnn** [comment]
嗯哼，辛苦辛苦

**Comment by kingwrcy** [comment]
![image](https://github.com/user-attachments/assets/7f8505a4-cafe-47a9-b40d-ad8a9c11ba8b)

使用的NuxtUI的Textarea组件,麻烦你用safari试试这2个输入框,看看打长一点的文本,会使Textarea本身变宽吗?我这里试下来只会变高,不会变宽.

[NuxtUI](https://ui.nuxt.com/components/textarea)

**Comment by slynnnn** [comment]
https://github.com/user-attachments/assets/dad4ea94-16a9-439a-8af1-2ecbe2c99d37

**Comment by slynnnn** [comment]
https://github.com/user-attachments/assets/663823bd-b914-472e-8b84-a8f31c4b0d1c

**Comment by kingwrcy** [comment]
貌似也有同样的问题,我以为是autoresize导致的,看你这个貌似是聚焦之后拉起输入框就有问题了.
第三个textarea控件是不带autoresize的,我看你也是有问题.

目前没啥好办法.

**Comment by slynnnn** [comment]
太深入的技术我就不太懂啦。也不是个很严重的bug ，只是使用上稍微有点不便利，有解决的办法时候在处理就行。辛苦辛苦
