### ISSUE TITLE
希望能再次优化打开速度

### ISSUE THREAD

**Issue by wang4386** [kingwrcy/moments#181]
目前首屏加载比上一版本有明显提升，但是依然稍慢，而且首次加载时，代码框有时丢失样式，或者是悬浮复制按钮需等待较长时间显现，另外希望添加链接的功能可以添加多个链接，依次在底部排列

**Comment by kingwrcy** [comment]
1. 关于加载慢的问题主要是Nuxt3打包之后的文件比较多,目前大概加载了5-60个js文件,虽然每个文件大小都很小,但是数量很多,这个有待进一步优化.
2. 代码块丢失样式,目前没有遇到.
3. 复制按钮本来就是页面加载完成后等5秒再使用js实现出来的.
4. 链接只支持1个,目前没有计划支持多个.

**Comment by adozhao** [comment]
支持瘦身，被速度耽误了不少，每次打开白屏时间太他么久了~~

`已解决，nginx ssl_ciphers 配置有问题导致，目前秒开~`

**Comment by adozhao** [comment]
@kingwrcy 你的nginx ssl配置方便发一下吗？我昨天搞完之后秒开，后来乱改东西，现在又给傻逼一样了，想看看你的ssl相关配置那里  
![image](https://github.com/user-attachments/assets/65ae5aa9-a982-414d-996d-76051be359e2)

**Comment by kingwrcy** [comment]
我自己部署的没有使用nginx,直接部署在laf云上面的,所以没有这个配置,看你这个配置也没看到什么问题的.

**Comment by adozhao** [comment]
> 我自己部署的没有使用nginx,直接部署在laf云上面的,所以没有这个配置,看你这个配置也没看到什么问题的.

我直接ip:port访问秒开，但是反向代理ssl后就变慢了，有几秒白屏，上次我改了下 ssl_ciphers 加密，突然也能秒开了，然后我又各种试验，导致之前的加密算法忘记了，尴尬
