### ISSUE TITLE
0.25 版本现在不支持显示指定行内容了？

### ISSUE THREAD

**Issue by 80imike** [kingwrcy/moments#184]
<img width="598" alt="image" src="https://github.com/user-attachments/assets/dfa3ba82-ff43-41e7-bddd-2a172dd064e4">

0.21 版本以后，后端转 go 就开始不支持显示指定行内容了？

0.20 以前是可以的，望大佬加入这个功能

内容太多了，展示不好看

**Comment by kingwrcy** [comment]
没理解是什么意思?是说最大显示的行数吗?
如果是这个的话,目前是可以设置最大高度,而不是最大行数了,因为支持了markdown语法.
