### ISSUE TITLE
memo查看权限异常

### ISSUE THREAD

**Issue by yylqing** [kingwrcy/moments#191]
版本号：v0.2.6
创建私密memo，id 1。
无需登录可以直接通过url： 域名/memo/1查看到这条私密内容。

希望权限可以分三个：public（公开），protect（登录查看），private（私密）

谢谢！

**Comment by xuewenG** [comment]
@yylqing @kingwrcy #197 尝试修复了越权访问 memo 的问题。新增权限类型涉及功能修改，是否符合“极简”的初心？建议进一步讨论

**Comment by kingwrcy** [comment]
> @yylqing @kingwrcy #197 尝试修复了越权访问 memo 的问题。新增权限类型涉及功能修改，是否符合“极简”的初心？建议进一步讨论

感谢 @xuewenG 的pr,这个跟极简不冲突,这是 私密 类型的memo权限没判断导致的,马上合并掉.
