### ISSUE TITLE
删除用户评论新增二次确认

### ISSUE THREAD

**Issue by adozhao** [kingwrcy/moments#192]
目前删除用户评论的交互好像有点太随意了，鼠标一点，评论就没了，缺少了点儿严肃感~

**Comment by dinphy** [comment]
> 目前删除用户评论的交互好像有点太随意了，鼠标一点，评论就没了，缺少了点儿严肃感~

已提交了PR，等待合并吧[https://github.com/kingwrcy/moments/pull/193](https://github.com/kingwrcy/moments/pull/193)

**Comment by kingwrcy** [comment]
已合并.下个版本发布.
