### ISSUE TITLE
请问一下，现在版本有 API 吗？

### ISSUE THREAD

**Issue by eallion** [kingwrcy/moments#194]
请问一下，现在版本有 API 吗？或者有没有其他不需要登录 APP 通过 API 发布信息的方式？

**Comment by kingwrcy** [comment]
有,参考[这里](https://discussion.mblog.club/post/pto2hqoFzDKzZMpvoPZKYuP),开启api文档

**Comment by wulintang** [comment]
> 有,参考[这里](https://discussion.mblog.club/post/pto2hqoFzDKzZMpvoPZKYuP),开启api文档

打不开这个链接。

**Comment by Jinvic** [comment]
> > 有,参考[这里](https://discussion.mblog.club/post/pto2hqoFzDKzZMpvoPZKYuP),开启api文档
> 
> 打不开这个链接。

见[Readme - 环境变量](https://github.com/kingwrcy/moments#%EF%B8%8F-%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F)

环境变量设置`ENABLE_SWAGGER`为`true`后，访问`/swagger/index.html`可以看到api文档。
