### ISSUE TITLE
手机端上传图片仅能选择一张

### ISSUE THREAD

**Issue by buqiaomuyudeheshang** [kingwrcy/moments#199]
目前使用手机端的网页进行上传图片时候，调用的系统图库，但是选择照片的时候只能选择一张，是否可以调整一下，同时选择多张照片上传呢。

**Comment by jkjoy** [comment]
什么手机什么浏览器?

**Comment by buqiaomuyudeheshang** [comment]
![Screenshot_20241015_140625](https://github.com/user-attachments/assets/95fd8134-24d4-4cb0-8090-d8c264e6381c)
iqoo的z9用的自带浏览器

**Comment by FanyiZeng** [comment]
试试对图片进行长按是否能激活多选？我是 vivo x fold 3 pro 最新系统是可以的

**Comment by kingwrcy** [comment]
我这没有这些手机,暂时无法复现这些问题,也没发修复.

**Comment by buqiaomuyudeheshang** [comment]
可能我手机的问题，我换华为手机也是没有问题的
