### ISSUE TITLE
在苹果手机的浏览器里把网站添加到主屏幕，无法获取图标

### ISSUE THREAD

**Issue by jolly90s** [kingwrcy/moments#201]
无法正常获取网站的图标，pin在主屏幕的图标就是黑底白字，能否修改一下，能够正常获取网站图标？谢谢

**Comment by xuewenG** [comment]
尝试实现了一下，自测没发现问题，可以也试一下 @kingwrcy @jolly90s

**Comment by jolly90s** [comment]
> 尝试实现了一下，自测没发现问题，可以也试一下 @kingwrcy @jolly90s

暂时是不是得自己编译一下试试？

**Comment by xuewenG** [comment]
> > 尝试实现了一下，自测没发现问题，可以也试一下 @kingwrcy @jolly90s
> 
> 暂时是不是得自己编译一下试试？

可以先使用 `ixuewen/moments:dev` 这个镜像来测试，等代码合入发布后再换回来。

注意：这个镜像包含未发布的测试代码，使用前需要做好数据备份。

**Comment by jolly90s** [comment]
> > > 尝试实现了一下，自测没发现问题，可以也试一下 @kingwrcy @jolly90s
> > 
> > 
> > 暂时是不是得自己编译一下试试？
> 
> 可以先使用 `ixuewen/moments:dev` 这个镜像来测试，等代码合入发布后再换回来。
> 
> 注意：这个镜像包含未发布的测试代码，使用前需要做好数据备份。

好了 可以显示了 大佬牛逼！
