### ISSUE TITLE
求大佬发布新版的时候能否顺便也发个二进制文件？

### ISSUE THREAD

**Issue by jolly90s** [kingwrcy/moments#207]
我是Windows Server用户，在虚拟机里用Docker效率实在感人。
由于我对开发一窍不通，照着论坛教程编译了半天也没生出个二进制文件，麻烦开发大佬能否连二进制文件也一起发了？
我想用这个项目一直记录我女儿的成长历程。万分感谢！

**Comment by kingwrcy** [comment]
下个版本我上传下.

**Comment by jolly90s** [comment]
> 下个版本我上传下.

多谢大佬，目前Docker目录下的数据库等相关文件，我拷出来放在Windows二进制的目录里，可以识别导入吗？

**Comment by kingwrcy** [comment]
可以的 这些都是通用的.

**Comment by jolly90s** [comment]
> 可以的 这些都是通用的.

感谢！
