### ISSUE TITLE
图片浏览器异常卡顿

### ISSUE THREAD

**Issue by FanyiZeng** [kingwrcy/moments#209]
使用 chrome 浏览器，手机是 vivo x fold 3 pro 16 + 512 最新系统，图片大小约 7M

https://github.com/user-attachments/assets/98101a46-ff65-49c2-b7c9-604a437421ba

**Comment by kingwrcy** [comment]
目前没加入服务端压缩图片的功能,无法解决图片过大的问题.推荐使用cdn,cdn提供商一般提供了压缩功能.
