### ISSUE TITLE
新的构建和发布流水线会引起异常

### ISSUE THREAD

**Issue by dinphy** [kingwrcy/moments#212]
[feat: 修改构建和发布流水线](https://github.com/kingwrcy/moments/commit/0cb83faed1f03ea443244f2849b67ce8a0128e3e)

会引起内容发布页面的工具栏在移动端浏览器点击时，弹不出来。
用之前的打包docker镜像，没问题。
亲测了。

**Comment by kingwrcy** [comment]
改流水线的意义是什么?比之前的好在哪里?说明下吧.

**Comment by dinphy** [comment]
> 改流水线的意义是什么?比之前的好在哪里?说明下吧.

太专业了，回答不上。你既然合并了，意义自然明了，好处也显而易见吧。我只是能用就用，不能用就摆烂，等你亲测、发布。

**Comment by dinphy** [comment]
亲测，已修复问题。
