### ISSUE TITLE
增加缩略图预览   单图溢出BUG

### ISSUE THREAD

**Issue by dinphy** [kingwrcy/moments#218]
![微信截图_20241128152131](https://github.com/user-attachments/assets/572e8634-0593-4038-98c2-b2ea8010d524)
单张图片超出内容区域。

**Comment by Secretlovez** [comment]
#219 这个问题在这里已经修复了。缩略图闪烁问题可能是缩略图文件不存在导致的，可以试试看下这个工具，生成下之前图片的缩略图文件 #[图片压缩](https://github.com/Secretlovez/CompressImg)
