### ISSUE TITLE
v0.2.6版本尝试添加js失效

### ISSUE THREAD

**Issue by Apicer** [kingwrcy/moments#220]
v0.2.6版本添加官方提供的统计网站访问量的js，在自定义js中添加保存后无效果，添加隐藏github star只有css样式能生效
![1732866051436](https://github.com/user-attachments/assets/51020746-d45e-4c08-af95-8699a00f7a3c)

**Comment by jkjoy** [comment]
那只能是你自己的问题,

**Comment by xuewenG** [comment]
不要使用 `DOMContentLoaded` 事件。目前自定义 JavaScript 脚本是通过 HTTP API 从服务端获取的，因此开始执行自定义脚本时， `DOMContentLoaded` 事件已经发出，表现为你的脚本没有执行。

**Comment by Apicer** [comment]
> 不要使用 `DOMContentLoaded` 事件。目前自定义 JavaScript 脚本是通过 HTTP API 从服务端获取的，因此开始执行自定义脚本时， `DOMContentLoaded` 事件已经发出，表现为你的脚本没有执行。

那该怎么增加统计网站访问量，我是初次搭建这个服务，不是很了解，麻烦给下示例什么的

**Comment by Apicer** [comment]
document
.querySelector(".footer")
.insertAdjacentHTML(
"afterend",
<div class='flex text-sm justify-center'><div id="busuanzi_container_site_pv">本站总访问量<span id="busuanzi_value_site_pv"></span>次</div></div>
);
var script = document.createElement("script");
script.src = "//busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js";
script.async = true;
document.head.appendChild(script);

去掉外面包裹的函数，只留里面的内容就可以了
