### ISSUE TITLE
Docker镜像中最新的Dev版本缩略图自动旋转90度

### ISSUE THREAD

**Issue by jolly90s** [kingwrcy/moments#222]
苹果手机没有问题，小米9 SE手机查看就会出现这个问题，不知道其他安卓会不会。
![80a19823709b587d49ac79d62144ece](https://github.com/user-attachments/assets/2b3324d8-fa10-49e9-9d0a-0b7751e230f1)
上面这个图是最新的Dev镜像，但是发布之前包括点击缩略图打开后就是正常的角度，如下两图
![18f473b61b10159d8a2df7b084dabf9](https://github.com/user-attachments/assets/79ebcad3-7448-4e46-858e-69b3dd402b1d)
![ada6e6725f671f63f450d1ae9c9e786](https://github.com/user-attachments/assets/4b06d0c0-c29c-440e-989f-34d0c21dea1c)

然后我退回上一个Dev版本的镜像，就恢复了正常 如下图
![b5659b8f9ff45fc46e33ee48221507b](https://github.com/user-attachments/assets/0ab6c705-ab8e-4140-bb62-ad387936f008)

再问一下 下一个正式版啥时候发布？希望一起发布 Windows版的二进制文件，我照着论坛里编译，没编译成功。windows下也比较方便手动压缩上传的图像

谢谢开发者们！

**Comment by xuewenG** [comment]
可以提供一下两次 dev 的版本号吗？在设置里面，类似于 `版本号: dev.202411281039.070c7cc`

**Comment by jolly90s** [comment]
> 可以提供一下两次 dev 的版本号吗？在设置里面，类似于 `版本号: dev.202411281039.070c7cc`

这个版本是缩略图自动旋转90度的：【版本号: dev.202411281039.070c7cc】
这个版本是正常的：【版本号: dev.202411131450.1aee952】
谢谢

**Comment by xuewenG** [comment]
@jolly90s @Secretlovez 

二进制文件会跟随下个版本发布，但是这个图片旋转的问题 *可能* 和新引入的缩略图预览 feature 有关，所以暂时还不能发布新版本。

可能的原因是当前的图片压缩未能正处理图片中的 `exif` 信息，造成图片的方向数据丢失，导致显示异常，正在寻找修复方法。

**Comment by xuewenG** [comment]
@jolly90s 问题已修复，请使用最新的 `dev` 镜像试一下。

注意：由于问题发生在缩略图的生成过程中，所以已经上传的图片在使用新版本后不会自动修复，需要重新上传图片。

**Comment by Secretlovez** [comment]
Window系统可以把之前图片拷出来，下载这个程序[win程序](https://github.com/Secretlovez/CompressImg/blob/master/dist/compreseImg.exe)，在同一文件夹下运行，重新生成压缩图片，再把压缩文件夹compress_file下文件拷回去即可；或者直接在服务器下运行[Linux版本程序](https://github.com/Secretlovez/CompressImg/blob/master/dist/compreseImg)，重新生成压缩图片

**Comment by jolly90s** [comment]
> @jolly90s 问题已修复，请使用最新的 `dev` 镜像试一下。
> 
> 注意：由于问题发生在缩略图的生成过程中，所以已经上传的图片在使用新版本后不会自动修复，需要重新上传图片。

好了，辛苦，多谢！

**Comment by jolly90s** [comment]
> Window系统可以把之前图片拷出来，下载这个程序[win程序](https://github.com/Secretlovez/CompressImg/blob/master/dist/compreseImg.exe)，在同一文件夹下运行，重新生成压缩图片，再把压缩文件夹compress_file下文件拷回去即可；或者直接在服务器下运行[Linux版本程序](https://github.com/Secretlovez/CompressImg/blob/master/dist/compreseImg)，重新生成压缩图片

好的，感谢指导！等Moments下个版本发行Windows二进制后，我把项目整个迁移到Windows中，就重新生成一下压缩图片。

**Comment by xuewenG** [comment]
没问题的话这个 issue 先关闭了，另外 v0.2.7 已经发布了。
