### ISSUE TITLE
顶部图片能否支持多张图片随机展示呢？

### ISSUE THREAD

**Issue by dianso** [kingwrcy/moments#228]
顶部图片能否支持多张图片随机展示呢？

预设多张图片

**Comment by xuewenG** [comment]
是想随机展示顶部图片吗？感觉不是很有必要，如果需要的人比较多的话，可以再考虑下。

此外，也欢迎各位朋友共建，代码没有问题的话可以合入。

**Comment by dinphy** [comment]
> 是想随机展示顶部图片吗？感觉不是很有必要，如果需要的人比较多的话，可以再考虑下。
> 
> 此外，也欢迎各位朋友共建，代码没有问题的话可以合入。

这个没必要，花里胡哨的

**Comment by dianso** [comment]
目前是用nginx来实现，一个地址随机展示图片。
