### ISSUE TITLE
如何删除作者的帖子

### ISSUE THREAD

**Issue by Skinsly** [kingwrcy/moments#237]
如何删除作者的帖子？

**Comment by jessicaliu2009** [comment]
看样子目前应该是没有编辑和删除功能，我也没找到

**Comment by Skinsly** [comment]
> 看样子目前应该是没有编辑和删除功能，我也没找到

写错内容怎么办？想删掉

**Comment by jolly90s** [comment]
在主页定位到你想要删除的帖子，点击这个帖子中你的头像（是头像不是昵称），进入到了单条帖子展示页面。页面右上角有三个点，点一下，下方会弹出置顶、编辑、删除三个选项

**Comment by Skinsly** [comment]
> 在主页定位到你想要删除的帖子，点击这个帖子中你的头像（是头像不是昵称），进入到了单条帖子展示页面。页面右上角有三个点，点一下，下方会弹出置顶、编辑、删除三个选项

感谢，终于找到了
