### ISSUE TITLE
请问在 urlos 这个环境下怎样安装？

### ISSUE THREAD

**Issue by linji1** [kingwrcy/moments#238]
https://www.urlos.com/ URLOS是基于Docker容器的云主机管理平台

您好，请问在这个平台下怎样安装？

**Comment by xuewenG** [comment]
没用过 URLOS，没法给出具体的操作步骤。目前只支持通用的安装方式，具体请参考 [使用教程](https://github.com/kingwrcy/moments?tab=readme-ov-file#%E4%BD%BF%E7%94%A8%E6%95%99%E7%A8%8B)
