### ISSUE TITLE
夜间模式风格优化

### ISSUE THREAD

**Issue by douseful** [kingwrcy/moments#24]
![CleanShot 2024-04-24 at 8 10 27@2x](https://github.com/kingwrcy/moments/assets/52767905/0c6550ac-190c-4f48-9641-b7d38b345ec5)
![CleanShot 2024-04-24 at 8 11 39@2x](https://github.com/kingwrcy/moments/assets/52767905/90e038d4-35f5-41ee-8189-50c797ae499b)
如图

**Comment by kingwrcy** [comment]
收到 下个版本处理下.

**Comment by kingwrcy** [comment]
设计如此的,就是想要间隔大些,留白大一点.
