### ISSUE TITLE
请问，已发的动态可以编辑或者删除吗

### ISSUE THREAD

**Issue by Peyjee-W** [kingwrcy/moments#244]

**Comment by dinphy** [comment]
点头像进入详情页，详情页右上角有三个点，点击就可以了

**Comment by ytcadsl** [comment]
右上角没有三个点啊我用的最新版的镜像

**Comment by Jinvic** [comment]
> 右上角没有三个点啊我用的最新版的镜像

![Image](https://github.com/user-attachments/assets/b7397ea8-db1a-424c-9a3e-02252d5c3bed)

在这里
