### ISSUE TITLE
如图，移动端优化一下

### ISSUE THREAD

**Issue by dinphy** [kingwrcy/moments#26]
![screenshot-1714005650285](https://github.com/kingwrcy/moments/assets/17978673/cba2ed05-8768-49a7-b990-61844cc3005b)

**Comment by kingwrcy** [comment]
收到,下个版本移动端 不显示中文.

**Comment by kingwrcy** [comment]
![image](https://github.com/kingwrcy/moments/assets/1247324/2661250d-9160-4e32-b526-9d0a93b007a6)
见 0215c907185cc4d68e0b28e13a0db2efe03a8747 下个版本发布
