### ISSUE TITLE
用变量控制单条发言最大行数时，存在 bug

### ISSUE THREAD

**Issue by 80imike** [kingwrcy/moments#29]
用变量控制单条发言最大行数时，存在 bug

NUXT_PUBLIC_MOMENTS_MAX_LINE 等于 6 以内 是正常控制的

<img width="729" alt="image" src="https://github.com/kingwrcy/moments/assets/1665201/be75b771-65c0-49e8-9856-3ab6d8325367">

当 NUXT_PUBLIC_MOMENTS_MAX_LINE 大于 6 ，比如值为 8 时 就会显示全部内容

<img width="773" alt="image" src="https://github.com/kingwrcy/moments/assets/1665201/7cbd618d-b316-4558-b98e-3a3fc79192e8">

**Comment by kingwrcy** [comment]
已修复 v0.1.0 版本,请更新
