### ISSUE TITLE
R2 怎么搞

### ISSUE THREAD

**Issue by jkjoy** [kingwrcy/moments#3]
S3貌似还不太一样

**Comment by kingwrcy** [comment]
一样的配置,要配置下跨域,不配置无法使用

[S3配置说明](https://github.com/kingwrcy/moments?tab=readme-ov-file#%E9%85%8D%E7%BD%AEs3)

**Comment by jkjoy** [comment]
看来R2还是不一样的

**Comment by jkjoy** [comment]
是不是可以自定义head 和 footer

**Comment by kingwrcy** [comment]
> 看来R2还是不一样的

试了下,R2不支持配置跨域所需的OPTIONS方法,放弃吧,R2用不了.

![image](https://github.com/kingwrcy/moments/assets/1247324/6aae9da0-118b-4d05-86d1-ded8991d803e)


> 是不是可以自定义head 和 footer

现在没有header,footer也没内容,唯一的内容就是github链接.暂不考虑支持自定义

**Comment by kingwrcy** [comment]
@jkjoy 经过研究,发现是支持R2的,按照[这篇文章](https://jerry.mblog.club/moments-r2-config)来配置即可.

有问题请反馈.

**Comment by jkjoy** [comment]
OK了,建议可以自定义footer 添加备案信息

**Comment by kingwrcy** [comment]
下个版本支持输入备案号。
