### ISSUE TITLE
内容编辑BUG

### ISSUE THREAD

**Issue by dinphy** [kingwrcy/moments#33]
编辑内容时出现的BUG，主要是有图片的内容，没有完全联动起来。如果点击有图片的内容编辑，还未提交，然后又去点击编辑纯文字的，或者编辑有内嵌链接的，这是就会出现有图片的内容，图片还在，没有跟随点击编辑其他内容而隐藏。
比如，我先编辑图文的内容，如下：
![微信截图_20240426171052](https://github.com/kingwrcy/moments/assets/17978673/5abe4e6c-2593-4302-8250-ceac5e0571c8)

编辑框是这样的
![微信截图_20240426171718](https://github.com/kingwrcy/moments/assets/17978673/00029032-cea5-4399-9e03-19f499bb1506)

我接着又点击编辑一个纯文字的，图片还在
![微信截图_20240426171849](https://github.com/kingwrcy/moments/assets/17978673/eed97e06-160d-4d5c-b12b-5d7f733bc1a6)

然后，我又去点击编辑有内嵌链接的，图片依然还在
![微信截图_20240426172103](https://github.com/kingwrcy/moments/assets/17978673/8e6ad0c3-97f3-461c-ab7d-658d348adf91)

但是编辑有图文的内容时，又是正常的。
![微信截图_20240426172118](https://github.com/kingwrcy/moments/assets/17978673/b11461c9-1706-4e87-ab5e-5cf866e4dcdd)

另外，如果能在编辑内容时滚动到编辑框位置的话，这样更方便操作，要么整个抽屉或者弹窗。离编辑框远的内容，点击了编辑以为没反应。

**Comment by kingwrcy** [comment]
明白，这是个bug，节后修复。

**Comment by dinphy** [comment]
> 明白，这是个bug，节后修复。

又发现新的BUG，编辑带音乐的内容，音乐输入框是空的，获取不到地址。如图
![screenshot-1714218983266](https://github.com/kingwrcy/moments/assets/17978673/ca0fcef1-758b-440d-a2e9-5cf9982dd1de)
