### ISSUE TITLE
可以实现不同用户登陆发布朋友圈 更好啦 可以 多用户使用

### ISSUE THREAD

**Issue by greejim** [kingwrcy/moments#34]
建议可以多用户登陆

**Comment by kingwrcy** [comment]
目前已有群友@RandallAnjie 自行实现了多用户版本，但问题还是不少，等后续需要的人多了，再合并进来。

**Comment by RandallAnjie** [comment]
多用户目前还存在很多未知问题，现在已经可以开放注册了，大家可以尝试注册反馈问题，目前兼容性还存在巨大问题，Safari，苹果系的浏览器全部不支持

**Comment by RandallAnjie** [comment]
多用户版本已经优化了一些，有需要的可以来看看了

**Comment by adozhao** [comment]
其实，我也很想要多用户

**Comment by zwjdujin** [comment]
> 目前已有群友@RandallAnjie 自行实现了多用户版本，但问题还是不少，等后续需要的人多了，再合并进来。

还可以考虑情侣空间，两个人的版本。

**Comment by kingwrcy** [comment]
v0.2.1已实现多用户,更新即可.
