### ISSUE TITLE
视频站位太宽

### ISSUE THREAD

**Issue by dinphy** [kingwrcy/moments#35]
如图，站位太宽了
![Screenshot_2024-04-27-14-23-38-73_df198e732186825c8df26e3c5a10d7cd](https://github.com/kingwrcy/moments/assets/17978673/0a8a3e39-7531-4296-87b0-86012b2bd58a)

能否优化成下图
![Screenshot_2024-04-27-14-23-13-05_df198e732186825c8df26e3c5a10d7cd](https://github.com/kingwrcy/moments/assets/17978673/1622881c-6e74-49a6-bebd-086d6b7fd520)

**Comment by kingwrcy** [comment]
不行,目前宽度铺满,无法读取视频原始长宽比例.
