### ISSUE TITLE
希望能支持传视频啊

### ISSUE THREAD

**Issue by SelfEnough** [kingwrcy/moments#39]
我的理解是可以当成一个私人的朋友圈，记录分享自己的生活点滴。
那多数时候可能就是手机操作，
手机直接记录，发送，图片还好，但是视频没办法直接上传，
有时候录了一段有趣的视频想要提交，
我还得先去找个平台上传发布获取链接，（这个可能还涉及到审核和时效）
于是我尝试用群晖自己的相册分享视频链接或者可道云的文件分享，但是那个外链都是下载页的外链，并不支持直接被当成视频引用。
所以最后我只能去搭个图床上传视频获取视频外链，

这样体验就蛮割裂的。
如果能直接支持传视频就好了。
或者说有什么好的解决方法吗？

**Comment by kingwrcy** [comment]
上传视频要考虑进度条，嫌麻烦暂时没弄，先加个没进度条的版本吧，下个版本加上。

**Comment by kingwrcy** [comment]
v0.1.2 已支持上传本地视频.
