### ISSUE TITLE
希望加上视频上传功能，手机APP的支持，我用memos客户端登录总是报错

### ISSUE THREAD

**Issue by xiehaoing** [kingwrcy/moments#41]
希望加上视频上传功能，手机APP的支持，我用memos客户端登录总是报错~

**Comment by kingwrcy** [comment]
没有客户端app,希望社区有人能一起开发一个.

至于上传本地视频,目前没有,下个版本准备加入.

**Comment by kingwrcy** [comment]
v0.1.2 已支持上传本地视频.
