### ISSUE TITLE
移动端适配的不咋好

### ISSUE THREAD

**Issue by wj6019** [kingwrcy/moments#42]
![Screenshot_20240505_121029](https://github.com/kingwrcy/moments/assets/106159209/7fed5661-536f-4e35-a9a2-2c29ad8fcb85)
有小半没显示出来

**Comment by kingwrcy** [comment]
![image](https://github.com/kingwrcy/moments/assets/1247324/a5fb029e-d1ec-4608-b209-f44b0d0dbb6e)

**Comment by aimdotsh** [comment]
iOS 移动端，safari 上传图片会严重拉长。
<img width="419" alt="image" src="https://github.com/kingwrcy/moments/assets/27554033/513d11b5-4e8a-47b7-b890-3bfc986d597c">

**Comment by kingwrcy** [comment]
更新到最新版本试试 v0.1.4

**Comment by aimdotsh** [comment]
可以了。
