### ISSUE TITLE
希望增加显示具体上传日期，而不是倒计时

### ISSUE THREAD

**Issue by xiehaoing** [kingwrcy/moments#43]
![PixPin_2024-05-05_21-33-17](https://github.com/kingwrcy/moments/assets/34760236/1cf73d7e-aae0-4a1e-9929-0aa19a9ef905)

希望增加显示具体上传日期，而不是倒计时

**Comment by kingwrcy** [comment]
v0.1.2版本已经支持,通过环境变量来设置.
