### ISSUE TITLE
希望把 邮件通知 功能放到设置里面

### ISSUE THREAD

**Issue by dinphy** [kingwrcy/moments#44]
希望把 邮件通知 功能放到设置里面，通过环境配置操作很不方便，也没有配置成功过。
设置里搞一个开关，可以默认关闭，需要的开启后在输入框里填写账号、密码、邮箱、发件人等信息。

**Comment by kingwrcy** [comment]
不考虑,配置项太多,一个一个加没有精力.
有其他人也同样无法使用配置文件正确的配置邮箱相关的参数吗?
我这里是可以的.

**Comment by kingwrcy** [comment]
发现好多人因为这个配置问题很多,下个版本改为通过界面配置.

预览图如下:


![image](https://github.com/kingwrcy/moments/assets/1247324/e0b6de50-12be-41ce-8e13-8b9db7aa0f2e)
