### ISSUE TITLE
如果能支持Markdown就无敌啦😂

### ISSUE THREAD

**Issue by yihanglee-cn** [kingwrcy/moments#5]
如果能支持Markdown就无敌啦😂
参考Markdown语法链接：https://www.appinn.com/markdown/

**Comment by kingwrcy** [comment]
支持md没问题，可是这本意是朋友圈，基本就是不太长的消息。

一共只有四行可展示，超过了就折叠了。不知道什么情况需要md?

图片和链接都已经支持了。
