### ISSUE TITLE
【建议】发布朋友圈之后不可更改

### ISSUE THREAD

**Issue by adozhao** [kingwrcy/moments#52]
建议发布朋友圈之后就不要再允许编辑了，否则会出现驴头不对马嘴的情况。

**Comment by dinphy** [comment]
> 建议发布朋友圈之后就不要再允许编辑了，否则会出现驴头不对马嘴的情况。

你文案写得好，可以不更改的，但编辑还是需要的

**Comment by adozhao** [comment]
> > 建议发布朋友圈之后就不要再允许编辑了，否则会出现驴头不对马嘴的情况。
> 
> 你文案写得好，可以不更改的，但编辑还是需要的

那比如本来的文案是“小白兔”，用户评论“小白兔真可爱“，然后你通过编辑把文案变为“大黄狗“，用户评论还是“小白兔真可爱”，请问这种情况，如何应对？

**Comment by kingwrcy** [comment]
@adozhao  你确定你不是来闹着玩的吗?

**Comment by adozhao** [comment]
> @adozhao 你确定你不是来闹着玩的吗?

怎么会闹着玩儿，我很认真的好不好，我觉得这是个问题呀，可以偷梁换柱~

**Comment by kingwrcy** [comment]
不会考虑.

目前都是单用户,你自己不改,谁还能帮你改了吗?

你可以不编辑,但是我不能没有编辑的能力吧,万一打错字了呢 对吧.

**Comment by adozhao** [comment]
> 不会考虑.
> 
> 目前都是单用户,你自己不改,谁还能帮你改了吗?
> 
> 你可以不编辑,但是我不能没有编辑的能力吧,万一打错字了呢 对吧.

从当前的实现来说确实没问题，我其实考虑的确实是多用户的问题，以后我觉得极大可能这个项目会发展成多用户，不过那时候搞也不迟
