### ISSUE TITLE
建议界面自定义配置粘贴时做基础性校验

### ISSUE THREAD

**Issue by adozhao** [kingwrcy/moments#55]
v0.1.3界面配置粘贴时没有做基础性校验，比如用户直接在配置的textarea中右键粘贴，可能此时的剪切板完全没有数据，此时配置项就被全部清空了。再或是如果粘贴的内容与期望的配置项不匹配，那么会不会导致整个项目崩溃，这个还没试。  

🙏感谢作者的辛苦付出，一直不断在更新代码！

**Comment by kingwrcy** [comment]
被清空了没关系,只要你不点保存就没事,点保存了,那也没辙.

至于基础性校验也只能判断是否为空和必须是个JSON字符串,其他的也无从判断了.

**Comment by kingwrcy** [comment]
已添加 ,请更新到最新版本.
