### ISSUE TITLE
官方提供了访问量统计代码，默认有点不太好看，有大神给美化下 css 吗？

### ISSUE THREAD

**Issue by 80imike** [kingwrcy/moments#57]
官方提供了访问量统计代码，默认有点不太好看，有大神给美化下 css 吗？

<img width="871" alt="image" src="https://github.com/kingwrcy/moments/assets/1665201/b4db2c9d-6e48-44d6-90dc-5676c4b3a084">

https://github.com/kingwrcy/moments/blob/master/q&a.md

document.addEventListener("DOMContentLoaded", () => {
  setTimeout(() => {
    document
      .querySelector(".footer")
      .insertAdjacentHTML(
        "afterend",
        `<div class='flex text-sm justify-center'><div id="busuanzi_container_site_pv">本站总访问量<span id="busuanzi_value_site_pv"></span>次</div></div>`
      );
    var script = document.createElement("script");
    script.src = "//busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js";
    script.async = true;
    document.head.appendChild(script);
  }, 500);
});

**Comment by adozhao** [comment]
可以自己用css处理下，我觉得默认还是挺好看的，就是没有间距

**Comment by kingwrcy** [comment]
自行处理,我这里只是给出方式.

审美这个东西,都是主观感受,万一等会再来个人说我就觉得之前的更好看,那我一直要帮你改到底吗?

给了你自行美化的能力,自己摸索下调成你自己觉得好看的样式吧.
