### ISSUE TITLE
建议与memos互联互通

### ISSUE THREAD

**Issue by ilikui** [kingwrcy/moments#58]
memos 地址 https://github.com/usememos/memos

**Comment by kingwrcy** [comment]
如何互通呢?举例说明

**Comment by ilikui** [comment]
例如使用Token将数据同步到memos里面

![image](https://github.com/kingwrcy/moments/assets/11962397/1f6a185f-7e92-4112-9856-b27f5dad960d)





> 如何互通呢?举例说明
