### ISSUE TITLE
希望支持游客可以随意留言，管理员可以设置所有内容仅管理员可见，游客只能看到*****

### ISSUE THREAD

**Issue by koujiangqq** [kingwrcy/moments#59]

**Comment by koujiangqq** [comment]
有些场合需要这个功能，因为留言内容不能让所有人都看到，但是又需要任何人都可以来发表意见，我们只需要收集意见并不需要人人都能看到这些内容导致一些不必要的争论

**Comment by kingwrcy** [comment]
暂无计划.

下个版本将支持管理员可见的私密发言,用户将看不见.只有自己登录了才能看见.

不支持显示为***,打码显示了,别人还怎么留言呢?都不知道发了什么还如何留言?

**Comment by koujiangqq** [comment]
期待下个版本，也许能解决我的大麻烦
