### ISSUE TITLE
有没有办法处理图片的显示方式？

### ISSUE THREAD

**Issue by dinphy** [kingwrcy/moments#60]
考虑到上传的图片不能压缩，在页面上加载时，带宽小的服务器老半天显示不出图片来，有没有办法处理一下呢？
比如预设一个图片懒加载之类的，或者前端默认显示图片的预览图，当用户点击查看时才显示原图（毕竟原图好几个MB）。

**Comment by kingwrcy** [comment]
使用S3提供的压缩功能.本地不会压缩.

一般的S3都会提供.

**Comment by adozhao** [comment]
我觉得这个需求以后肯定是有必要去实现的，把压缩图片的功能融入到moments本体，可以以插件开关的形式提供

**Comment by kingwrcy** [comment]
> 我觉得这个需求以后肯定是有必要去实现的，把压缩图片的功能融入到moments本体，可以以插件开关的形式提供

因为压缩需要引入一些第三方库，这会导致每次上传图片对服务端有压力，也会拖慢上传速度。

反观外面的s3,基本都原生支持这个功能，更有水印，缩略图，防盗链等强大的功能，而且基本都有免费额度，我实在不知道这么执着于本地上传的是什么想法？

本项目的立意就在于极简，这个s3已经完全支持的功能我个人认为没有必要造轮子。

如果你不知道哪些s3可以免费使用，包括压缩图片的功能，我这里推荐你使用[缤纷云](https://www.bitiful.com/)，利益无关.

个人正常使用是免费的。

**Comment by adozhao** [comment]
我用的minio，支持s3协议，好像原生不带图片处理功能
