### ISSUE TITLE
修改昵称后存量的评论的昵称没有对应更改

### ISSUE THREAD

**Issue by adozhao** [kingwrcy/moments#64]
评论里回复之后，如果修改昵称的话，之前的回复没有同步变更，很难被识别为同一个人

**Comment by kingwrcy** [comment]
这个不会更改的,评论的名字不是唯一的,你爱叫啥叫啥.

不会去更新别人的名字的,因为你没办法证明你和那个人是一个人.

**Comment by adozhao** [comment]
> 这个不会更改的,评论的名字不是唯一的,你爱叫啥叫啥.
> 
> 不会去更新别人的名字的,因为你没办法证明你和那个人是一个人.

我试了一下，在登录的情况下，修改昵称后之前的没有跟着变更，这时候是能识别同一个人的

**Comment by adozhao** [comment]
> > 这个不会更改的,评论的名字不是唯一的,你爱叫啥叫啥.
> > 不会去更新别人的名字的,因为你没办法证明你和那个人是一个人.
> 
> 我试了一下，在登录的情况下，修改昵称后之前的没有跟着变更，这时候是能识别同一个人的，目前的实现是只要评论了，评论者的昵称就永远不会改变

**Comment by adozhao** [comment]
> > > 这个不会更改的,评论的名字不是唯一的,你爱叫啥叫啥.
> > > 不会去更新别人的名字的,因为你没办法证明你和那个人是一个人.
> > 
> > 
> > 我试了一下，都是在登录的情况下，修改昵称后，之前的评论没有跟着变更，实际上此时是能识别为同一个人的，  

目前的实现是只要评论了，评论者的昵称就永远不会改变

**Comment by kingwrcy** [comment]
登录的人默认会取自己的昵称,如果你改了,那就没办法.

之前的昵称不会改的,这个试你自己改的.
