### ISSUE TITLE
什么时候能够直接更改管理员密码啊

### ISSUE THREAD

**Issue by tianmaozhi** [kingwrcy/moments#92]
大佬，因为不懂技术，实在不知道5555怎么打开，尝试在终端里面输入了命令，然后浏览器打开IP:5555结果进不去，能不能直接在网页端更改管理员密码 啊

**Comment by kingwrcy** [comment]
你登陆进去了设置页面可以改。

没登陆进去忘了密码的话，随便找个在线管理sqlite的工具改下数据库user表的password字段就行。
