### ISSUE TITLE
Timezone issue

### ISSUE THREAD

**Issue by 2ndMessiah** [kingwrcy/moments#93]
Hi King,

Thx for your product!! It works like a charm!

I found something weird today, as the post time has dropped behind 12 hours from now.
<img width="150" alt="image" src="https://github.com/kingwrcy/moments/assets/22229188/f35016c8-46d6-42d9-b695-14f0c3722fca">

/etc/timezone and /etc/localtime has been added to compose.yml. And my Linux system clock is correct as shown below:
<img width="378" alt="image" src="https://github.com/kingwrcy/moments/assets/22229188/267a2861-7d40-4ed2-a6c4-91e2bf58004f">

Can't figure it out. Hope there's a reason.

Thx again.

**Comment by kingwrcy** [comment]
1. Check the timezone in your docker container,not the Linux Host system.
2. Check the real time filed in your sqlite database,the table name of `memo`,filed name is `createdAt`

**Comment by 2ndMessiah** [comment]
> 1. Check the timezone in your docker container,not the Linux Host system.
> 2. Check the real time filed in your sqlite database,the table name of `memo`,filed name is `createdAt`

Thx for the reply! I entered the container(/bin/sh) to check the timezone and date situation, and they're correct as the same as the host:
![image](https://github.com/kingwrcy/moments/assets/22229188/a9317fb9-8c8a-42eb-a42a-ebcf1f2892b4)

So I tested it again but it's still 12hrs dropped behind.
![image](https://github.com/kingwrcy/moments/assets/22229188/83c3e59d-113e-4ac5-9013-97ecf9491207)

My compose.yml:
![image](https://github.com/kingwrcy/moments/assets/22229188/de38cde1-0955-4bc5-b838-08f9009ee0cf)

**Comment by kingwrcy** [comment]
What is the time zone of your computer? It's not the server, it's the computer you use to browse the website.

If your computer's time zone is also GMT+8, open F12 and check the network request to see if the data returned by the server is correct?

Moments uses the dayjs library to format dates, which may read your local computer's time zone.

**Comment by 2ndMessiah** [comment]
> What is the time zone of your computer? It's not the server, it's the computer you use to browse the website.
> 
> If your computer's time zone is also GMT+8, open F12 and check the network request to see if the data returned by the server is correct?
> 
> Moments uses the dayjs library to format dates, which may read your local computer's time zone.

Same Shanghai timezone. I switched a couple of devices and all of them display the wrong time.

I didn't notice this problem cuz the "date format" option is the default as below. I set it to display the full date time yesterday and found this.
![image](https://github.com/kingwrcy/moments/assets/22229188/a91e36e5-1c2b-4cd4-8314-66e27832e064)

**Comment by kingwrcy** [comment]
If possible, post your moments address and I'll take a look.

**Comment by 2ndMessiah** [comment]
> If possible, post your moments address and I'll take a look.

Thx for ur devotion to this!! Here's the [link](https://pyq.g999.ru).

**Comment by kingwrcy** [comment]
Found the issue.

https://github.com/kingwrcy/moments/blob/103ff4f51d35775d93abd01557737438c1a2c3af/components/FriendsMemo.vue#L61

Currently the 12-hour clock is used, not the 24-hour clock.

Next version will fix this issue.

**Comment by kingwrcy** [comment]
fixed in v0.1.6
