### ISSUE TITLE
提一个关于功能建议

### ISSUE THREAD

**Issue by tianmaozhi** [kingwrcy/moments#94]
看到您在上一个版本中新增了点击头像进入所点击博文的详情，但是如果看完了能不能直接点击头像返回到主页，且要回到这篇博文所在的上下文页面

**Comment by dinphy** [comment]
> 看到您在上一个版本中新增了点击头像进入所点击博文的详情，但是如果看完了能不能直接点击头像返回到主页，且要回到这篇博文所在的上下文页面

页面上有返回箭头啊。
